DROP DATABASE API;
CREATE DATABASE API;
USE API;

CREATE TABLE GRUPOS(
IDGRUPO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) UNIQUE NOT NULL
);
SELECT * FROM GRUPOS;
INSERT INTO GRUPOS (NOME) VALUES ('ADM');
INSERT INTO GRUPOS (NOME) VALUES ('USER');

CREATE TABLE USUARIOS(
IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
SENHA VARCHAR(100) NOT NULL,
GRUPO VARCHAR(100) NOT NULL,
FOREIGN KEY (GRUPO) REFERENCES GRUPOS(NOME)
);

